### ISSUE TITLE
Logo formats (Responsive Images)

### ISSUE THREAD

**Issue by Robin1224** [Shannafdnd/user-experience-enhanced-website#2]
Ookal gebruik je geen foto's uit Directus in je project, zou je misschien alsnog Responsive Images met PE kunnen toepassen met het logo. Op dit moment wordt het logo geserveerd in webp, wat al goed is, maar er zijn misschien browsers die dit niet ondersteunen.

Omdat het bestand op je eigen website gehost staat, kun je dit denk ik het beste aanpakken door het zelf te converteren naar AVIF en PNG (bijvoorbeeld via https://ezgif.com/webp-to-avif, https://cloudconvert.com/webp-to-png), en deze naast je .webp bestand te zetten.

Vervolgens kun je deze aan de hand van Progressive Enhancement toepassen in je pagina. Dit zou je bijvoorbeeld kunnen doen door de volgende code:

https://github.com/Shannafdnd/user-experience-enhanced-website/blob/1f551229ea706b5ec230a896ccba4b7ab92eb0c2/views/partials/header.ejs#L22-L24

Te veranderen naar een `<picture>` element, zoals bijvoorbeeld:

```html
<a href="/">
    <picture>
        <source srcset="/assets/RedPers_Logo_Cmyk_Black.avif" type="image/avif">
        <source srcset="/assets/RedPers_Logo_Cmyk_Black.webp" type="image/webp">
        <img class="logo" src="/assets/RedPers_Logo_Cmyk_Black.png" alt="Red Pers logo">
    </picture>
</a> 
```

Met deze code zorg je ervoor dat, als een browser AVIF ondersteunt, hij het logo in AVIF formaat krijgt (dit is de snelste), ondersteunt hij dit niet, dan doet hij hetzelfde met WebP. En als de browser ouder is, en beiden van deze formaten niet ondersteunt (of het picture element zelf niet snapt), dan neemt het gewoon het logo in PNG.

Zo zorg je ervoor dat je logo ook nog werkt op browsers die WebP niet ondersteunen, maar hou je het bestand alsnog klein en snel op nieuwere browsers.

**Comment by Shannafdnd** [comment]
Thx, ik was het logo helemaal vergeten, zal er naar kijken.
